[driver]
driver_backend = "harbor"
pool = "terminal-bench@2.0"
pattern = "eager"
max_concurrent = 1
n_task = 2
results_dir = "tests/output/con-driver"
sample_without_replacement = true
# task_subset_start = 0
# task_subset_end = 2
port_profile_id = 1
# port_profile_id_list = [1, 2]
# max_concurrent_list = [1, 1]
agent = "terminus-2"
